title: A Beautiful Daze 
author: April Treacy
email: afontaine0612@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An entrepreneur mommy who shares in her adventures as she juggles homeschool, autism, neverending messes, attitudes, and her own schooling all while managing a business with her hubby. 
# social links
github_username:  April-Treacy

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
